### ISSUE TITLE
Internal constant missing - Sys Range Offset

### ISSUE THREAD

**Issue by ajsb85** [adafruit/Adafruit_CircuitPython_VL6180X#18]
**Application note AN4545**
_VL6180X basic ranging application note_

![image](https://user-images.githubusercontent.com/663460/120518079-77c65580-c3d1-11eb-8ca5-a1c0e382f7be.png)

Other libraries that support this settings:

https://github.com/sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library
https://github.com/pololu/vl6180x-arduino

**Comment by ladyada** [comment]
pull requests welcome!

**Comment by tekktrik** [comment]
I've really wanted to try my hand at I2CDevice actually, I can take this!

**Comment by tekktrik** [comment]
Hardware to test is on the way, will check in when I've got it working or otherwise need help.  Then I'll submit the PR!

Branch with proposed change in my fork: https://github.com/tekktrik/Adafruit_CircuitPython_VL6180X/tree/feature/add-manual-offset

**Comment by tekktrik** [comment]
@ajsb85 I submitted a pull request, let me know if this fits how you're using it!

**Comment by tekktrik** [comment]
Resolved by #22
