### ISSUE TITLE
Handling power loss?

### ISSUE THREAD

**Issue by broakenmedia** [adafruit/Adafruit_CircuitPython_VL6180X#30]
Hello,

I'm using the VL6180X to detect the presence of an object in front of. Everything works great except it seems to choke up in the event of a power loss.

```
try:
    while True:
        try:
            current_time = monotonic()
            range_mm = proximitySensor.range
            light_lux = proximitySensor.read_lux(adafruit_vl6180x.ALS_GAIN_1)
            if range_mm <= 30 and current_time - last_launch_time >= launch_interval:
                last_launch_time = current_time
                print('success')
            sleep(0.5)
        except OSError:
            print("Lost Power")
            continue
except KeyboardInterrupt:
        print("Ending")
```

While power is attached, the loop runs and output 'success' without issue when the object is detect. I am to then unplug the external power supply such that the sensor is without power it moves into the 'Lost Power' part of the loop. Corrrect. Upon restoring the power, the loop begins anew but then hangs forever on `proximitySensor.range` - Reading the docs i was not able to see anything i can do to query the status of the sensor after this point nor how i might be able to kick it back into life.

Any help with this would be greatly appreciated!

Thanks.

**Comment by caternuson** [comment]
You'll need to recreate the `proximitySensor` instance so that the sensor initialization setup code also runs again once power is restored.

**Comment by broakenmedia** [comment]
Gotcha, i'll set a variable on OSError and check to reinit on the next loop. Best thing i can think of.

**Comment by FoamyGuy** [comment]
This looks to be resolved by the comments above. Feel free to re-open or create a new issue if there is still some problem
