### ISSUE TITLE
The read_lux() function always returns 0

### ISSUE THREAD

**Issue by djipco** [adafruit/Adafruit_CircuitPython_VL6180X#31]
Each time I call the `read_lux()` function, I always get a value of `0`. I have tried specifying various gain values (per the [documentation](https://docs.circuitpython.org/projects/vl6180x/en/latest/api.html#adafruit_vl6180x.VL6180X.read_lux)) but it does not change anything.

I know the sensor works because the `range` property reports correct values. I should mention that I had to remove `rpi-gpio` in favour of `rpi-lgpio` to make it work on my Pi 5 (otherwise, I was getting an error):

```sh
sudo apt remove python3-rpi.gpio
pip3 install rpi-lgpio
```

This is the code I'm using:

```python
import board
import busio
import adafruit_vl6180x

i2c = busio.I2C(board.SCL, board.SDA)
sensor = adafruit_vl6180x.VL6180X(i2c)

while True:
	distance = sensor.range # This works
	luminosity = sensor.read_lux(adafruit_vl6180x.ALS_GAIN_5) # This does not work
	time.sleep(0.1)
```

Could it be a compatibility issue with Pi 5 ? Something else?

Thank you.

**Comment by FoamyGuy** [comment]
I tested this library and sensor on a Feather S3 TFT and a RPi 4 both ran successfully and did output correct lux values above zero. I will test on a Pi 5 next.

**Comment by FoamyGuy** [comment]
I tested on a Pi 5 successfully as well getting correct non-zero values for lux. I used a fresh pi 5 imaged with latest raspi OS 64bit and the automated blinka setup instructions detailed here: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

Closing this for now feel free to re-open or create a new issue if you're still having trouble with latest versions of everything.
